# Nom du pipeline
name: Mon premier pipeline

# Critère d'exécution (trigger)
on:
  push:
    branches: [ new-branch ]

# Le vrai pipeline
jobs:
  # Le nom de ton job (ce que tu veux)
  hello:
    # Pas besoin d'y toucher
    runs-on: ubuntu-latest

    # Liste des étapes de ton pipeline
    steps:
    # Récupérer le code (on le fait toujours)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Hello
      run: echo 'Hello World !!!'
  salut:
    runs-on: ubuntu-latest
    steps: 
      - name: salut
        run: echo 'Salut!!!'

  goodbye:
    runs-on: ubuntu-latest
    
    steps:
    - name: goudbye
      run: echo 'Goodbye World.'

  salutbienlafamille:
    runs-on: ubuntu-latest
    
    steps:
    - name: salutbienlafamille 
      run: echo 'Salut bien la famille.'
  
  byebye: 
    needs:
    runs-on: ubuntu-latest

    steps: 
    - name: byebye
      run: echo 'Bye Bye'