# Nom du pipeline
name: Mon premier pipeline

# Critère d'exécution (trigger)
on:
  push:
    branches: [ main ]

# Le vrai pipeline
jobs:
  # Le nom de ton job (ce que tu veux)
  test:
    # Pas besoin d'y toucher
    runs-on: ubuntu-latest

    # Liste des étapes de ton pipeline
    steps:
    # Récupérer le code (on le fait toujours)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Hello
      run: echo 'Hello World !!!'

  deploy:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4